## Sub-bottom Acoustics

Acoustic stratigraphy from six Transects (@fig-map-lake) reveal the range of morphologies and character of infilling sedimentary deposits in Cariboo Lake (@fig-acoustics). Acoustic penetration is limited in Transects A and E by coarse sediments proximal to river fan-deltas across Cariboo Lake (see triangle symbols in @fig-map-lake for fan-delta locations). Acoustic signal penetration, resolution and distinctive acoustic layering improves significantly along the thalweg of the lake bottom away from the main Cariboo River delta along Transects B, C, and D. In the Frank Creek and Keithley Creek sub-basins acoustic penetration is reduced along Transect E and F, respectively. The diagonal lines across all panels (cross-hatching) in @fig-acoustics is observed over most of the acoustic record due to errant electrical interference from the research vessel that could not be resolved. However, the interference does not affect the overall quality of the acoustic results in the six Transects (@fig-acoustics).

Transect B, 3.5 km from the Cariboo River delta, has acoustic reflectors with 1-2 m separation that lie conformably over a hummocky basement (@fig-acoustics, B - i). The acoustic basement drops off below the observable record near the south channel-like depression. Well-structured layering extends across the south side of the Transect but pinches out towards the north shore (@fig-acoustics). On the south side of Transect B, the thickness of acoustically well-stratified deposits ranges from 10 to 20 m.

Acoustic penetration in the acoustic record increases 4.5 km from the Cariboo River delta along Transect C, where the maximum sediment thicknesses of 35 m are observed (@fig-acoustics, C). The acoustic basement is interpreted to be either bedrock or coarse-grained glacial sediment from the Last Glacial Maximum (@fig-acoustics, C – i). Two sediment facies are observed above the acoustic basement based on geometry and the strength and continuity of reflectors. The lower unit, facies A, has a thickness of ~12 m along undisturbed sections (@fig-acoustics, C - A) and is more massive to weakly acoustically layered. Two sharp-crested v-shaped notches in the middle of Transect C are interpreted as unconformities (@fig-acoustics, C). The channels are the same as those in Transect B (@fig-acoustics, B) and are interpreted to be scour channels formed by erosive, higher energy, turbidity currents that likely date to deglaciation of the lake basin. Facies A is comprised of a lighter grey tone representing coarse-grained sediment and lacks parallel reflectors indicating a higher energy and more rapid deposition of coarser lacustrine sediment. Facies B begins with high-amplitude parallel reflectors with 2-3 m separation and conforms well with facies A below (@fig-acoustics, C). Facies B has an average thickness of ~10 m and reaches a maximum thickness of 13 m where it infills two scour channels (@fig-acoustics, C - ii & iii). 

Transect D, to the northeast of the Frank Creek delta has well-layered sediments in the top 5-10 m and transitions to poor acoustic penetration below this (@fig-acoustics, D). The parallel reflectors observed in the uppermost sediment layers of Transect D have a thickness of 2-3 m and have a higher amplitude compared to facies B in Transect C. Some slumping of sidewall sediments is observed on the south sidewall (@fig-acoustics, D).