## Spatial Trends in Surficial Sediment {#spatial}

The surficial sediment cores show declining trends in grain size and laminae thickness with distance from the main Cariboo River delta. Trends in percent organic matter (OM) of surficial sediment cores were not found to exhibit systematic patterns with distance down-lake (@fig-ekmanSeds, C). The steep decline in grain size suggests that larger sand-sized sediments (63–2000 µm) are sensitive to distance from fan deltas, while smaller silt-sized (2–63 µm) and clay-sized (0.01–2 µm) sediments are transported further down-lake. The highest percent of silt (86.5–89.6%) and clay (9.3–14.4%) sized sediments are observed between 3 and 6.5 km from the Cariboo River delta, proximal to the long core sampling locations. Higher D~50~ grain size and percentage of sand sized grains were also found proximal to the Frank Creek fan-delta and within the Keithley Creek sub-basin (@fig-ekmanSeds, A & B). 

Proximal to the Cariboo River delta the structure of the surficial sediments exhibits massive layering, erosive contacts and the fraction of sand grains greater than 60%. A sand-bed with a thickness of 1 cm was observed in E1, the core closest to the Cariboo River delta (@fig-ekmanImgs, A). In the main Cariboo River basin, core E13, retrieved 5.24 km from the Cariboo River delta and from a depth of 40 m, contained fine, rhythmically laminated sediment (@fig-ekmanImgs, B).

Sediment cores E9–E15 and E18–E20, retrieved from areas distal to the main Cariboo River delta, at lake depths of 30–50 m, have a high fraction of silt and clay sediment and exhibit a rhythmic sequence of fine-grained dark layers overlain by coarse-grained light layers (@fig-ekmanImgs, B & C). The sediment stratigraphy observed within cores E9–E15 and E18–E20 are similar to annual laminations (varves), which occur in lakes that have sufficient seasonal variation in river and sediment discharge as well as lake stratification [@Cockburn2008; @Zolitschka2015a; @Heideman2015; @Hodder2006b; @Desloges1999]. In the Cariboo Lake basin, winter low flows, lake-ice cover, and lake stratification reduce the velocity of lake currents and contribute to the deposition of fine-grained sediments on the lake bottom. During spring snowmelt high flows, coarser-grained sediments are deposited from higher energy lake currents. Additional deposition of coarse-grained sediment may also result from abnormally high discharge events caused by large rainfall events, rain-on-snow events, rapid melt of glaciers and snowpack during heat waves, and/or turbidity currents due to delta collapse [@sabatier2022]. Coastal lakes in western Canada that are frequented by large rainstorms and mid-winter melt events exhibit multiple laminae couplets deposited in a given year [@Menounos2008c]. However, the distinct spring snowmelt-dominant hydrological regime of the Cariboo Lake watershed suggests the deposit of multiple coarse-grained laminae in a single year is rare (@fig-cl-hydro). Coarse-grained deposits are still possible in Cariboo Lake due to turbidity currents from delta slumping/foreset failures, however turbidites were only observed in Ekman cores proximal to river deltas (e.g. @fig-ekmanImgs, A). While the sediment stratigraphy of Ekman cores E9–E15 and E18–E20 resemble varves, further analysis of the Cariboo Lake long-cores and ^14^C chronology are used to confirm this.