## Sediment Accumulation Chronology

### Chronology  

Organic material for ^14^C dating in the clastic dominated cores was extremely limited. AMS ^14^C dates obtained for cores V1 and V2 are presented in @tbl-amsDates and provide limited temporal control and evidence of sediment accumulation rates for the long cores. A small twig from V1 at 343 cm and a conifer needle and twig which were combined into one sample at V2, with an average depth of 281 cm, yielded ages 1740–1880 cal yr BP and 1870–2040 cal yr BP, respectively. @fig-amsRates shows the ^14^C chronology for V1 and V2 compared to the laminae couplet chronologies for V1, and V2. The ^14^C dates from samples V1 and V2 yield accumulation rates of 1.81 ± 0.07 mm yr^-1^ and 1.37 ± 0.05 mm yr^-1^ respectively. A search for tephra was made through careful magnified inspection of visual colour changes. None were found using this method. @Westgate1977, @Hallett1997 and @Maurer2012b indicate that this area of British Columbia has had episodic volcanic ash inputs from significant eruptions that predate 2100 yr BP but nothing since.

Ekman surficial core 13 (E13) is most proximal to the V2 long core (@fig-map-lake) and exhibits similar sediment accumulation compared to the V1 and V2 ^14^C chronology and laminae chronology of V2 (@fig-amsRates, inset). If one couplet corresponds to one year of sedimentation, then the resulting sediment accumulation rate would be 1.98 ± 0.19 mm yr^-1^, which is consistent with those computed from the ^14^C chronologies of V1 and V2 (@fig-amsRates). The light-dark couplets shown in @fig-ekmanImgs, are similar to annual deposits noted in dozens of other varved lakes throughout BC [e.g., @Hodder2006b]. Therefore, the couplets within the Ekman cores are interpreted as varves. Higher accumulation rates are expected for the Ekman samples as they are not subjected to the same level of compaction as deeper sediment in the long cores.

By comparison with nearby lakes, accumulation rates in areas proximal to river inputs in Quesnel Lake were measured to be about 0.72 mm yr^-1^ [@Gilbert2012]. Sediment inputs are expected to be lower in the much larger Quesnel Lake compared to Cariboo Lake, with more arid and less glaciated portions of the Quesnel Lake watershed contributing to that lower rate. The AMS accumulation rates of 1.81 ± 0.07 mm yr^-1^ and 1.37 ± 0.05 mm yr^-1^ in Cariboo Lake are as expected for a smaller watershed with a higher fraction of glacier cover compared to Quesnel Lake [@Hodder2006b]. The ^14^C dates from samples V1 and V2 provide an important control when interpreting the inferred temporal pattern of sediment inputs to Cariboo Lake.

Three distinct sediment facies were observed in both V1 and V2: discernible couplets, indiscernible couplets (disturbed facies) and graded turbidites. The similarity in couplet structure and thickness between cores V1 and V2 and processes that deliver sediment into Cariboo Lake strongly suggested these are varves. This interpretation is also supported by the two ^14^C dated samples from cores V1 and V2 which corresponded reasonably well with the couplet count chronology at the same depth (@fig-amsRates). The slightly lower sediment accumulation rate at V2 is interpreted to be due to its location 3 km further down lake. Differences between the ^14^C and varve chronologies for each core were attributed to uncertainties with couplet counting and AMS ^14^C dating. Turbidite deposits in core V1 and V2 were depositional and not erosive suggesting the removal of couplets by turbidity currents was not an important factor contributing to missing varves.   

The uncertainty of the laminae counting method is inferred from Ekman surface cores by counting laminae down to a common specified depth of 5 cm for three Ekman cores E12, E13, E14 which are proximal to V1 and V2 (@fig-map-lake). The Ekman laminae counting analysis resulted in an uncertainty estimate of the counting method of about 10% or 1 miscounted varve per 10 years. This counting error of 10% is higher than the varve counting error of 0.7% in @Menounos2008c and 0.7–6% in @Zolitschka1991. The number of multiple coarse-grained layers deposited within a single year (false varves) is estimated to be less than the number of missing varves. The low frequency of false varves is supported by the distinct spring melt regime of the Cariboo Lake basin, which results in the deposition of the coarse-grained layer over the high flow period (@fig-cl-hydro). The negative bias of the varve chronology compared to the calibrated ^14^C age-depth model shown in @fig-amsRates also suggests that false varves are rare and that undercounting may be a more important source of counting error. In addition to undercounting attributed to couplets with indiscernible laminae, the potential loss of sediment from the top of the long cores could have also contributed to missing varves. 

Turbidites were identified if laminae/beds had D~50~ grain size greater than 3 standard deviations from the mean, a uni-modal grain size distribution and/or visual identification of normal grading within the beds. @fig-varve-turb examples show the difference in regular laminae compared to a turbidite bed. Turbidite beds observed in V1 and V2 were well defined with normal grading (@fig-varve-turb, d). These turbidite beds are similar in structure to those described in @sabatier2022 as originating from a flood, glacial lake outburst flood, or delta collapse event. Since the Cariboo River upstream of Cariboo Lake is filtered by headwater proglacial lakes, it is likely the coarse sediment grains observed within the turbidite beds at the distal V1 and V2 sites are from localized sidewall tributary floods. Collapse of the foreslope of an oversteepened Cariboo delta is also possible.

Where possible the thickness, grain size statistics, and percent organic matter (OM) were analyzed for each turbidite. The increased grain size and greater thickness of the turbidites illustrate the high sediment flux during these events compared to the annual couplets (@tbl-turbTbl). The composition of sediment grains within the turbidites were all characterized by a coarser single mode with less than 0.01% clay, over 98% silt and less than 1% sand. The grain size distribution for the annual couplet sediments is characterized as bi-modal with an average composition of 16% clay, 83% silt, and less than 1% sand. @fig-amsRates shows that most turbidites observed within V1 and V2 occurred at similar times. Since each of the turbidites contain sediment deposited over a single, potentially localized event, they were removed from the varve-based chronology and trend analyses of varve thickness, grain size, and percent organics.

The varve-based chronology is based on the counting of discernible couplets with turbidite beds removed. Indiscernible couplets in the disturbed-massive units makes interpreting the time elapsed over each of these units difficult (@fig-varve-turb, C). To compensate for the depth intervals associated with the disturbed sections, a 30-year moving average of sediment accumulation rates from immediately above and below the disturbed sections were used to interpolate accumulation rates over each facies [see method described in @Menounos2008c]. For core V1, couplets were counted down to a core depth of 343 cm, where the organic material for ^14^C dating was retrieved. This resulted in a couplet-derived age estimated of 1460 ± 150 yr BP compared to the two-sigma calibrated ^14^C age range of 1740–1880 cal yr BP. For core V2, the couplet-derived age for the organic material at a depth of 281 cm was 1792 ± 180 yr BP compared to the ^14^C age range of 1870–2040 cal yr BP. The better alignment between the couplet counting age and the AMS derived age in V2 can be attributed to the larger number of sections in V1 that had indiscernible couplets compared to V2. Sections with indiscernible couplets were interpolated using a moving average and may also have a greater number of missing varves which may have contributed to the larger negative bias in the V1 varve counting record shown in @fig-amsRates. Despite the substantial uncertainty in both the varve counting and AMS ^14^C dating methods, there is evidence to suggest the laminae couplets are deposited annually. The strongest evidence is for core V1 where there is an overlap of the varve and ^14^C chronology uncertainty bounds (@fig-amsRates). In addition, the varve counting age of the turbidites shown in @fig-amsRates have relatively close agreement between between cores V1 and V2. Additional ^14^C analysis is required to conclusively determine the couplets are varves, however the majority of evidence presented here suggests this is the case.

The basal age for each core is estimated using both the varve counting method and a linear extrapolation of the ^14^C chronology. The basal age of V1 at 378 cm is approximately 1580 ± 160 yr BP based on the varve chronology and the two-sigma calibrated ^14^C range is 1930–2080 cal yr BP. The basal age of V2 at 282 cm is about 1800 ± 180 varve yr BP based on the varve chronology and the two-sigma calibrated ^14^C range is 1910–2060 cal yr BP. The closer alignment of the ^14^C and varve chronology at V2 gives greater confidence in the V2 age model used for reconstructing the timing of Holocene sedimentation patterns for this core. Since V1 has a greater spread between the two chronologies, there is less confidence in the chronology of this core. However, given the physical mechanisms that control sedimentation in Cariboo Lake it is likely both cores primarily contain couplets that are deposited annually.

### Sediment Laminae Statistics

A time series of varve thickness (as standardized departures) is presented in @fig-varves-a, using only discernible couplets. Turbidites have been removed and indiscernible facies are represented as gaps. The chronology for this time series was derived using a linear interpolation from the median calibrated ^14^C date of each core (@tbl-amsDates). The mean varve thickness for V1 is 2.4 mm and for V2 is 1.5 mm. The time series of varve thickness measured from V1 and V2 illustrates trends in suspended sediment delivery to Cariboo Lake (@fig-varves-a). The 30-year average varve thickness are largely above average from 2000–1200 cal yr BP, for both V1 and V2, with a stronger signal observed for V1 which is closer to the main Cariboo River outlet. Below average varve thickness is observed at both V1 and V2 from 1200–350 cal yr BP. After 350 cal yr BP, trends in varve thickness between the two cores depart, with V2 above average during the Little Ice Age and V1 remains below average. Sub-centennial trends are not reported due to the coarse temporal control for both V1 and V2.

#### Grain Size

The mean D~50~ grain size is 7.6 ± 0.01 µm at V1, which is closer to the Cariboo River delta, compared to 6.3 ± 0.01 µm at V2. The temporal pattern in standardized departures of D~50~ grain size between the two cores shows a consistent pattern (@fig-proxy-comparison, C). Both V1 and V2 have above average grain size between 2000–1250 cal yr BP and below average from 1250–450 cal yr BP. After 450 cal yr BP, grain size follows an increasing trend with average to above average grain size. V1 shows an earlier increase in grain size compared to V2. While couplet thickness does not increase substantially over the LIA interval, gain size does. Overall, grain size fluctuations at a temporal resolution of about 100-years shows good correspondence between the two cores over the last 2000 years.

#### Organic Matter

The average percent organic matter (OM) of V1 and V2 is similar at 4.76% and 4.80%, respectively, suggesting that the flux of allochthonous organic material to the core locations is not dependent on distance from the main Cariboo River as it is easily transported through the lake due to low density. This is also supported by OM measured within the Ekman bulk samples, where a systematic down-lake relationship was not observed (@fig-ekmanSeds, C). Higher levels of organic content are shown in V1 and V2 from 2000–1000 cal yr BP and mostly below average from 1000–0 cal yr BP (@fig-proxy-comparison, B). Specific periods of above average OM for V1 occur around cal yr BP 1900–1450, 1300–800, around 650 and 200–100 OM in V2 matches above average values in the interval cal yr BP 1700–1400 and 1300–1000 (@fig-proxy-comparison, B).